### ISSUE TITLE
Invalid character in IE

### ISSUE THREAD

**Issue by morgante** [mathiasbynens/he#31]
In IE10, I get an error when trying to include he via a Browserify bundle.

The error is:
```
Invalid character
mergedAssets.min.8516d96.js (5,33406)
```

Which points to here in he:
```
"caret",Ç:"caron"
```

**Comment by mathiasbynens** [comment]
Which minifier do you use?

**Comment by morgante** [comment]
UglifyJS

**Comment by Maprunner** [comment]
I had the same problem, using grunt-contrib-uglify, which itself uses UglifyJS2. It turned out that it wasn't putting quotes around certain characters in the minified file. IE objects to this and raises a "SCRIPT1014: Invalid character" error. Firefox and Chrome are quite happy to process the minified file.

In the end I did an npm update and it is now putting quotes around everything so IE is happy. grunt-contrib-uglify hasn't changed, so it must be one of the dependencies, but unfortunately I'm not sure which one.

**Comment by stereokai** [comment]
This is probably a non-issue already and can be closed. Can we get a second verification?

**Comment by mathiasbynens** [comment]
Closing as I cannot reproduce the issue using `he.js` from this repository.
