### ISSUE TITLE
Parser issue on IE after JS minification.

### ISSUE THREAD

**Issue by gsaini** [mathiasbynens/he#40]

**Comment by mathiasbynens** [comment]
Which version of IE? What error are you getting?

**Comment by gsaini** [comment]
I meet the issue on IE10, IE11 as Illegal character at column 1746 somewhere at key as ^ in encodeMap variable without string quotes.

**Comment by anko** [comment]
What minifier did you use? Does this only happen on IE?

A [minimal test case](http://stackoverflow.com/help/mcve) would help.

**Comment by gsaini** [comment]
Yes. It's IE specific issue. I am using r.js to minify JS. I used the
minified version from Google CDN as well it also have the same issue.

**Comment by mathiasbynens** [comment]
@gsaini Is _he_ available on Google CDN? That is new to me.

**Comment by gsaini** [comment]
I used the below cdnjs url...
https://cdnjs.cloudflare.com/ajax/libs/he/0.5.0/he.min.js

**Comment by gsaini** [comment]
@mathiasbynens - Any update??

**Comment by anko** [comment]
@gsaini Does the non-minified version at `https://cdnjs.cloudflare.com/ajax/libs/he/0.5.0/he.js` work?

If it does, then the problem is with some minification that cdnjs is doing independently (which is out of our control) so you might want to raise this on the [cdnjs issue tracker](https://github.com/cdnjs/cdnjs/issues) instead.

**Comment by gsaini** [comment]
@anko - Yes it is some JS minification related issue which needs to fix for IE. I minified it with r.js (RequireJS) build system as well but it has the same issue on IE after minification.
